info:
    serviceLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}"
    podLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view-instance?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}&var-instance={podName}"


management:
    health.status.order: DOWN, OUT_OF_SERVICE, UNKNOWN, COMMENT, UP
    security:
        enabled: false


endpoints:
    health:
        mapping:
            COMMENT: OK
    metrics:
        enabled: false
    logfile:
        enabled: false
    autoconfig:
        enabled: false
    heapdump:
        enabled: false
    configprops:
        enabled: false
    mappings:
        enabled: false
    beans:
        enabled: false
    dump:
        enabled: false
    jolokia:
        enabled: false

openshift:
    url: https://utv-master.paas.skead.no:8443

boober:
  git:
    url: "https://git.aurora.skead.no/scm/oc/"
    username: "boober"
    password: "komogsyngensang"
spring:
  profiles:
    active: development


metrics:
  resourceUseCollectInterval: "300000"

logging:
  level:
    ske.aurora: DEBUG
    ske.aurora.filter: INFO
    org:
      jboss: INFO
      hibernate: WARN
      springframework: WARN
      apache:
        catalina: INFO
        velocity: INFO



---
spring:
  profiles: development


management:
    port: 8081


---
spring:
  profiles: openshift
