info:
    serviceLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}"
    podLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view-instance?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}&var-instance={podName}"

openshift:
    url: https://utv-master.paas.skead.no:8443
    cluster: utv

boober:
  encrypt:
    key: "komogsyngensang"
  git:
    url: "https://git.aurora.skead.no/scm/oc"
    checkoutPath: "/tmp/boober"
    username: "boober"
    password: "komogsyngensang"

management:
    health.status.order: DOWN, OUT_OF_SERVICE, UNKNOWN, COMMENT, UP
    security:
        enabled: false
    port: 8081

endpoints:
    health:
        mapping:
            COMMENT: OK
    metrics:
        enabled: false
    logfile:
        enabled: false
    autoconfig:
        enabled: false
    heapdump:
        enabled: false
    configprops:
        enabled: false
    mappings:
        enabled: false
    beans:
        enabled: false
    dump:
        enabled: false
    jolokia:
        enabled: false
spring:
  profiles:
    active: development

logging:
  level:
    no.skatteetaten: DEBUG
    ske.aurora.filter: INFO
    org:
      jboss: INFO
      hibernate: WARN
      springframework: WARN
      apache:
        catalina: INFO
        velocity: INFO

---
spring:
  profiles: development


---
spring:
  profiles: openshift
